"""
Setup command for the NVD CLI.

Commands:
    nvd setup      - Interactive first-run setup for NVD
    nvd shell-hook - Output shell integration code
"""

from __future__ import annotations

import getpass
import hashlib
import os
import shutil
import socket
import subprocess
import tempfile
import urllib.error
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax
from typer._completion_shared import get_completion_script

from py_nvd import __version__
from py_nvd.cli.utils import (
    console,
    error,
    get_editor,
    info,
    success,
    warning,
)
from py_nvd.paths import get_config_dir, get_setup_conf_path

# Separate console for stderr output (used by shell-hook to not pollute stdout)
stderr_console = Console(stderr=True)

# Default paths. INSTALL_HOME is the versioned repository checkout root used by
# install.sh. Generic runtime configuration defaults to ~/.config/nvd, but CHTC
# keeps per-user runtime files under ~/.nvd and shares only the preset store.
INSTALL_HOME = Path.home() / ".nvd"
CHTC_SHARED_DIR = Path("/staging/groups/oconnor_group/nvd")
CHTC_DEFAULT_CONFIG_DIR = INSTALL_HOME
CHTC_DEFAULT_PRESET_STORE = CHTC_SHARED_DIR / "presets.sqlite"
CHTC_DEFAULT_TAXONOMY_DIR = CHTC_SHARED_DIR / "taxdump"


def _is_oconnor_chtc() -> bool:
    """
    Detect if running on O'Connor lab CHTC access point.

    Checks hostname pattern: oconnor-ap*.chtc.wisc.edu
    """
    hostname = socket.gethostname()
    fqdn = socket.getfqdn()
    return hostname.startswith("oconnor-ap") and "chtc.wisc.edu" in fqdn


def _detect_shell() -> str | None:
    """
    Detect the user's shell from $SHELL environment variable.

    Returns:
        "bash", "zsh", or None if unrecognized.
    """
    shell_path = os.environ.get("SHELL", "")
    if not shell_path:
        return None

    shell_name = Path(shell_path).name
    if shell_name in ("bash", "zsh"):
        return shell_name

    return None


def _check_pixi_installed() -> bool:
    """
    Check if pixi is available on the system PATH.

    The wrapper script generated by setup uses `pixi run` to invoke nvd,
    so pixi must be globally installed for the wrapper to work.
    """
    return shutil.which("pixi") is not None


def _get_chtc_template_path() -> Path:
    """Get path to the CHTC config template shipped with the package."""
    # The template is in conf/ relative to the package root
    # We can find it relative to this file's location
    this_file = Path(__file__)
    # setup.py is at lib/py_nvd/cli/commands/setup.py
    # conf/ is at repo root, so go up 5 levels
    repo_root = this_file.parent.parent.parent.parent.parent
    return repo_root / "conf" / "chtc-template.config"


def _load_and_substitute_template(template_path: Path) -> str:
    """
    Load a config template and substitute variables.

    Variables substituted:
        ${HOSTNAME} - Current hostname
        ${USER} - Current username
        ${DATE} - Current date in ISO format
        ${VERSION} - NVD version
        ${HOME} - User's home directory (literal $HOME for Nextflow)
    """
    if not template_path.exists():
        msg = f"Template not found: {template_path}"
        raise FileNotFoundError(msg)

    template = template_path.read_text()

    # Substitute variables
    # Note: ${HOME} is left as literal $HOME for Nextflow to expand at runtime
    substitutions = {
        "${HOSTNAME}": socket.gethostname(),
        "${USER}": getpass.getuser(),
        "${DATE}": datetime.now(UTC).strftime("%Y-%m-%d"),
        "${VERSION}": __version__,
        # ${HOME} is intentionally NOT substituted - Nextflow needs it as-is
    }

    result = template
    for var, value in substitutions.items():
        result = result.replace(var, value)

    return result


def _preview_config(config_content: str) -> None:
    """Display config preview with syntax highlighting."""
    syntax = Syntax(
        config_content,
        "groovy",  # Nextflow config is Groovy-based
        theme="monokai",
        line_numbers=True,
    )
    panel = Panel(
        syntax,
        title="Generated user.config",
        border_style="cyan",
    )
    console.print(panel)


def _edit_config_in_editor(config_content: str) -> str:
    """
    Open config in user's editor and return the edited content.

    Creates a temp file, opens it in the editor, waits for the editor
    to exit, then reads and returns the (possibly modified) content.
    """
    editor = get_editor()

    # Create temp file with .config extension for editor syntax highlighting
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".config",
        delete=False,
    ) as f:
        f.write(config_content)
        temp_path = Path(f.name)

    try:
        # Open editor and wait for it to exit
        subprocess.run([editor, str(temp_path)], check=True)  # noqa: S603

        # Read back the (possibly edited) content
        return temp_path.read_text()
    finally:
        # Clean up temp file
        temp_path.unlink(missing_ok=True)


def _write_config(config_content: str, config_path: Path) -> None:
    """Write config to file, creating parent directories if needed."""
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_content)


DEFAULT_WRAPPER_DIR = Path.home() / ".local" / "bin"

WRAPPER_TEMPLATE = """\
#!/bin/bash
# NVD wrapper - runs nvd directly from pixi environment
# Generated by: nvd setup v{version}
# Date: {date}
#
# This wrapper sets PATH to include pixi environment binaries (for nextflow, etc.)
# but only for the nvd process - it doesn't pollute the user's shell PATH.

NVD_REPO="{nvd_repo}"
NVD_BIN="$NVD_REPO/.pixi/envs/default/bin"

# Verify the environment exists
if [[ ! -x "$NVD_BIN/nvd" ]]; then
    echo "Error: nvd not found at $NVD_BIN/nvd" >&2
    echo "Run 'pixi install' in $NVD_REPO to set up the environment." >&2
    exit 1
fi

# Run nvd with pixi bin on PATH (for subprocess access to nextflow, etc.)
PATH="$NVD_BIN:$PATH" exec "$NVD_BIN/nvd" "$@"
"""

SETUP_CONF_TEMPLATE = """\
# NVD setup configuration
# Generated by: nvd setup v{version}
# Date: {date}

NVD_REPO={nvd_repo}
NVD_CONFIG_DIR={config_dir}
{taxonomy_dir_line}
{preset_store_line}
{default_profile_line}
"""

_TAXONOMY_DIR_LINE_SET = "NVD_TAXONOMY_DB={taxonomy_dir}"
_TAXONOMY_DIR_LINE_COMMENT = "# NVD_TAXONOMY_DB=/shared/path/taxdump"

_PRESET_STORE_LINE_SET = "NVD_PRESET_STORE={preset_store}"
_PRESET_STORE_LINE_COMMENT = "# NVD_PRESET_STORE=/shared/path/presets.sqlite"

# Profile line templates
_PROFILE_LINE_SET = "NVD_DEFAULT_PROFILE={profile}"
_PROFILE_LINE_COMMENT = """\
# Default Nextflow profile for 'nvd run' (optional)
# Uncomment and set to use a custom profile by default:
# NVD_DEFAULT_PROFILE=my_profile"""


def _find_nvd_repo() -> Path:
    """
    Find the NVD repository root.

    Looks for the repo by traversing up from this file's location,
    looking for pyproject.toml with the nvd package.
    """
    # This file is at lib/py_nvd/cli/commands/setup.py
    # Repo root is 5 levels up
    this_file = Path(__file__)
    repo_root = this_file.parent.parent.parent.parent.parent

    # Verify it looks like the NVD repo
    pyproject = repo_root / "pyproject.toml"
    if pyproject.exists() and "nvd" in pyproject.read_text():
        return repo_root.resolve()

    msg = f"Could not find NVD repository root. Expected pyproject.toml at: {pyproject}"
    raise FileNotFoundError(msg)


def _get_stable_repo_path(repo_path: Path) -> Path:
    """
    Get a stable path to the NVD repo that survives version upgrades.

    If the repo is installed in the versioned directory structure
    (~/.nvd/v{version}/), returns ~/.nvd/latest instead of the versioned
    path. This ensures that setup.conf and the wrapper script remain
    valid after upgrades that rename the versioned directory.

    For repos in other locations (e.g., development clones), returns
    the original path unchanged.
    """
    resolved = repo_path.resolve()
    nvd_home = INSTALL_HOME.resolve()
    latest_link = nvd_home / "latest"

    is_versioned_install = resolved.parent == nvd_home and resolved.name.startswith("v")
    if not is_versioned_install:
        return resolved

    if not latest_link.is_symlink():
        return resolved

    try:
        latest_points_here = latest_link.resolve() == resolved
    except OSError:
        return resolved

    if not latest_points_here:
        return resolved

    return latest_link


def _generate_wrapper_script(nvd_repo: Path) -> str:
    """Generate the wrapper script content."""
    return WRAPPER_TEMPLATE.format(
        version=__version__,
        date=datetime.now(UTC).strftime("%Y-%m-%d"),
        nvd_repo=nvd_repo,
    )


def _generate_setup_conf(
    nvd_repo: Path,
    config_dir: Path,
    default_profile: str | None = None,
    preset_store: Path | None = None,
    taxonomy_dir: Path | None = None,
) -> str:
    """Generate the setup.conf content."""
    if default_profile:
        profile_line = _PROFILE_LINE_SET.format(profile=default_profile)
    else:
        profile_line = _PROFILE_LINE_COMMENT
    if preset_store is not None:
        preset_store_line = _PRESET_STORE_LINE_SET.format(preset_store=preset_store)
    else:
        preset_store_line = _PRESET_STORE_LINE_COMMENT
    if taxonomy_dir is not None:
        taxonomy_dir_line = _TAXONOMY_DIR_LINE_SET.format(taxonomy_dir=taxonomy_dir)
    else:
        taxonomy_dir_line = _TAXONOMY_DIR_LINE_COMMENT

    return SETUP_CONF_TEMPLATE.format(
        version=__version__,
        date=datetime.now(UTC).strftime("%Y-%m-%d"),
        nvd_repo=nvd_repo,
        config_dir=config_dir,
        taxonomy_dir_line=taxonomy_dir_line,
        preset_store_line=preset_store_line,
        default_profile_line=profile_line,
    )


def _install_wrapper_script(
    nvd_repo: Path,
    wrapper_dir: Path = DEFAULT_WRAPPER_DIR,
) -> Path:
    """
    Install the wrapper script.

    Creates the wrapper directory if needed, writes the script,
    and makes it executable.

    Returns the path to the installed wrapper.
    """
    wrapper_dir.mkdir(parents=True, exist_ok=True)
    wrapper_path = wrapper_dir / "nvd"

    wrapper_content = _generate_wrapper_script(nvd_repo)
    wrapper_path.write_text(wrapper_content)

    # Make executable (chmod +x)
    wrapper_path.chmod(wrapper_path.stat().st_mode | 0o111)

    return wrapper_path


def _write_setup_conf(
    nvd_repo: Path,
    config_dir: Path,
    default_profile: str | None = None,
    preset_store: Path | None = None,
    taxonomy_dir: Path | None = None,
) -> Path:
    """
    Write the setup.conf file to ~/.nvd/.

    This file stores the NVD_REPO path, config directory, and optional
    default profile for the shell hook and nvd run to read.
    """
    conf_path = get_setup_conf_path()
    conf_path.parent.mkdir(parents=True, exist_ok=True)

    conf_content = _generate_setup_conf(
        nvd_repo,
        config_dir,
        default_profile,
        preset_store,
        taxonomy_dir,
    )
    conf_path.write_text(conf_content)

    return conf_path


def _generate_completions(shell_type: str) -> Path:
    """
    Generate static shell completion file.

    Creates a completion script at ~/.nvd/completions.{shell} that can be
    sourced directly, avoiding the need to run nvd on every shell startup.

    Args:
        shell_type: "bash" or "zsh"

    Returns:
        Path to the generated completion file.
    """
    assert shell_type in ("bash", "zsh"), f"Unsupported shell: {shell_type}"

    script = get_completion_script(
        prog_name="nvd",
        complete_var="_NVD_COMPLETE",
        shell=shell_type,
    )
    if shell_type == "bash":
        script = _guard_bash_completion_script(script)

    completions_path = get_config_dir() / f"completions.{shell_type}"
    completions_path.parent.mkdir(parents=True, exist_ok=True)
    completions_path.write_text(script)

    return completions_path


def _guard_bash_completion_script(script: str) -> str:
    """Skip bash completion registration when sourced outside bash."""
    return script.replace(
        "complete -o default -F _nvd_completion nvd",
        "if type complete >/dev/null 2>&1; then\n    complete -o default -F _nvd_completion nvd\nfi",
    )


SHELL_HOOK_MARKER = "nvd setup shell-hook"


def _get_rc_file(shell_type: str) -> Path:
    """Get the RC file path for the given shell type."""
    if shell_type == "zsh":
        return Path.home() / ".zshrc"
    # bash
    return Path.home() / ".bashrc"


def _is_hook_installed(rc_file: Path) -> bool:
    """Check if the shell hook is already installed in the RC file."""
    if not rc_file.exists():
        return False
    return SHELL_HOOK_MARKER in rc_file.read_text()


def _install_shell_hook(rc_file: Path) -> bool:
    """
    Install the shell hook into the RC file.

    Appends the eval line to the RC file. Returns True on success,
    False if there was a permission error.
    """
    hook_line = f'eval "$({SHELL_HOOK_MARKER})"'
    hook_block = f"""
# NVD shell integration
{hook_line}
"""

    try:
        with rc_file.open("a") as f:
            f.write(hook_block)
        return True
    except PermissionError:
        return False


def _validate_config_dir(path: Path) -> tuple[bool, str]:
    """
    Validate a config directory path.

    Checks:
    1. Path exists or can be created
    2. Path is writable

    Returns:
        (is_valid, message) tuple
    """
    if path.exists():
        if not path.is_dir():
            return False, f"Path exists but is not a directory: {path}"
        # Check if writable by trying to create a temp file
        test_file = path / ".nvd_write_test"
        try:
            test_file.touch()
            test_file.unlink()
            return True, "Directory exists and is writable"
        except PermissionError:
            return False, f"Directory exists but is not writable: {path}"
        except OSError as e:
            return False, f"Directory exists but write test failed: {e}"
    else:
        # Check if parent exists and is writable
        parent = path.parent
        if not parent.exists():
            return False, f"Parent directory does not exist: {parent}"
        # Try to create the directory
        try:
            path.mkdir(parents=True, exist_ok=True)
            return True, f"Created directory: {path}"
        except PermissionError:
            return False, f"Cannot create directory (permission denied): {path}"
        except OSError as e:
            return False, f"Cannot create directory: {e}"


def _prompt_config_dir(default: Path, non_interactive: bool) -> Path:
    """
    Prompt user for config directory with validation.

    In non-interactive mode, just returns the default.
    """
    if non_interactive:
        return default

    console.print(f"Config directory [{default}]: ", end="", markup=False)
    user_input = input().strip()

    if not user_input:
        return default

    return Path(user_input).expanduser().resolve()


RELEASE_BASE_URL = "https://dholk.primate.wisc.edu/_webdav/dho/projects/lungfish/InfinitePath/public/%40files/release-v3.0.0/v3.0.0"
CHECKSUMS_URL = f"{RELEASE_BASE_URL}/checksums_v3_0.txt"
CONTAINER_IMAGE_URL = f"{RELEASE_BASE_URL}/nvd-v3.0.0-rc.sif"
CONTAINER_IMAGE_NAME = "nvd-v3.0.0-rc.sif"
_CHECKSUM_LINE_MIN_PARTS = 2
_MD5_HEX_LENGTH = 32
_SHA256_HEX_LENGTH = 64


def _get_container_path() -> Path:
    """Get the path where the container image should be stored."""
    return INSTALL_HOME / CONTAINER_IMAGE_NAME


def _download_url(url: str, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url) as response, destination.open("wb") as output:  # noqa: S310 - fixed HTTPS release URL
        shutil.copyfileobj(response, output)


def _fetch_checksum_manifest() -> str | None:
    try:
        with urllib.request.urlopen(CHECKSUMS_URL, timeout=30) as response:  # noqa: S310 - fixed HTTPS release URL
            return response.read().decode("utf-8")
    except (OSError, UnicodeDecodeError, urllib.error.URLError) as e:
        warning(
            f"Could not fetch checksum manifest; continuing without checksum verification: {e}",
        )
        return None


def _checksum_for_file(manifest: str, filename: str) -> str | None:
    for line in manifest.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parts = stripped.split()
        if len(parts) < _CHECKSUM_LINE_MIN_PARTS:
            continue
        checksum, path = parts[0], parts[1].lstrip("*").removeprefix("./")
        if path == filename or Path(path).name == filename:
            return checksum
    return None


def _verify_checksum(path: Path, expected: str) -> tuple[bool, str]:
    if len(expected) == _MD5_HEX_LENGTH:
        actual = hashlib.md5(path.read_bytes()).hexdigest()  # noqa: S324 - file integrity, not security
        algorithm = "MD5"
    elif len(expected) == _SHA256_HEX_LENGTH:
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        algorithm = "SHA256"
    else:
        return (
            True,
            f"Unsupported checksum length for {path.name}; skipping verification",
        )

    if actual != expected:
        return (
            False,
            f"Checksum mismatch for {path.name} ({algorithm}): expected {expected}, got {actual}",
        )
    return True, f"Checksum verified for {path.name} ({algorithm})"


def _pull_apptainer_image() -> tuple[bool, str]:
    """
    Pull the NVD container image using Apptainer.

    Returns:
        (success, message) tuple
    """
    sif_path = _get_container_path()

    # Ensure ~/.nvd exists
    sif_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        _download_url(CONTAINER_IMAGE_URL, sif_path)
        manifest = _fetch_checksum_manifest()
        if manifest is None:
            return True, f"Container image downloaded to {sif_path}"
        expected = _checksum_for_file(manifest, CONTAINER_IMAGE_NAME)
        if expected is None:
            warning(
                f"No checksum entry found for {CONTAINER_IMAGE_NAME}; continuing without checksum verification",
            )
            return True, f"Container image downloaded to {sif_path}"
        verified, message = _verify_checksum(sif_path, expected)
        if not verified:
            return False, message
        return True, f"Container image downloaded to {sif_path}. {message}"
    except (OSError, urllib.error.URLError) as e:
        return False, f"Container download failed: {e}"


setup_app = typer.Typer(
    name="setup",
    help="First-run setup and shell integration",
    no_args_is_help=False,
)


@setup_app.callback(invoke_without_command=True)
def setup(
    ctx: typer.Context,
    non_interactive: bool = typer.Option(
        False,
        "--non-interactive",
        help="Skip all prompts, use defaults or fail if required input missing",
    ),
    shell: str | None = typer.Option(
        None,
        "--shell",
        help="Shell to configure (bash, zsh). Auto-detected if not specified.",
    ),
    config_dir: Path | None = typer.Option(
        None,
        "--config-dir",
        help="NVD configuration directory (default: NVD_CONFIG_DIR or ~/.config/nvd)",
    ),
    skip_shell_hook: bool = typer.Option(
        False,
        "--skip-shell-hook",
        help="Don't install shell hook",
    ),
    skip_container: bool = typer.Option(
        False,
        "--skip-container",
        help="Don't pull container image (CHTC only)",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        help="Overwrite existing configuration without prompting",
    ),
) -> None:
    """
    Interactive first-run setup for NVD.

    This command configures NVD for your environment:

    1. Detects your environment (CHTC O'Connor lab vs generic)
    2. Creates user.config under NVD_CONFIG_DIR / ~/.config/nvd
    3. Installs a shell hook for PATH, environment variables, and completions
    4. On CHTC, optionally pre-pulls the Apptainer container image

    After setup, 'nvd' will be available in new shell sessions with
    tab completion and the correct config directory configured.

    Examples:

        # Interactive setup (recommended for first-time users)
        nvd setup

        # Non-interactive setup with custom config directory
        nvd setup --non-interactive --config-dir /scratch/nvd-config

        # Re-run setup, overwriting existing config
        nvd setup --force
    """
    # If a subcommand was invoked, don't run the main setup
    if ctx.invoked_subcommand is not None:
        return

    info("NVD Setup")
    console.print()

    # Check for pixi first - required for wrapper script
    if not _check_pixi_installed():
        error(
            "pixi not found\n\n"
            "NVD requires pixi for environment management. Install it with:\n"
            "  curl -fsSL https://pixi.sh/install.sh | bash\n\n"
            "Then run 'nvd setup' again.",
        )
        raise typer.Exit(1)

    # Detect environment
    is_chtc = _is_oconnor_chtc()
    if is_chtc:
        console.print(
            f"[green]Detected:[/green] CHTC O'Connor Lab access point ({socket.getfqdn()})",
        )
    else:
        console.print("[green]Detected:[/green] Generic system")

    # Detect shell (use provided or auto-detect)
    detected_shell = shell or _detect_shell()
    if detected_shell:
        console.print(f"[green]Detected shell:[/green] {detected_shell}")
    else:
        warning("Could not detect shell from $SHELL")

    console.print()

    if config_dir is not None:
        effective_config_dir = config_dir.expanduser().resolve()
    elif is_chtc:
        effective_config_dir = _prompt_config_dir(
            CHTC_DEFAULT_CONFIG_DIR,
            non_interactive,
        )
    else:
        effective_config_dir = _prompt_config_dir(get_config_dir(), non_interactive)

    os.environ["NVD_CONFIG_DIR"] = str(effective_config_dir)

    config_path = get_config_dir() / "user.config"
    should_write_config = False

    if is_chtc:
        # Check if config already exists
        if config_path.exists() and not force:
            if non_interactive:
                warning(f"Config already exists: {config_path}")
                warning("Use --force to overwrite")
                # Don't write config, but continue to wrapper script installation
            else:
                console.print(f"[yellow]Config already exists:[/yellow] {config_path}")
                overwrite = typer.confirm("Overwrite existing config?", default=False)
                if overwrite:
                    should_write_config = True
                else:
                    info("Keeping existing config")
                    console.print()
        else:
            should_write_config = True

        if should_write_config:
            # Load and substitute template
            template_path = _get_chtc_template_path()
            if not template_path.exists():
                error(f"CHTC config template not found: {template_path}")
                raise typer.Exit(1)

            config_content = _load_and_substitute_template(template_path)

            # Preview config
            console.print("Setting up NVD for CHTC HTCondor/OSPool execution...")
            console.print()
            _preview_config(config_content)
            console.print()

            # Offer to edit (interactive mode only)
            if not non_interactive:
                edit = typer.confirm("Edit this config in your editor?", default=False)
                if edit:
                    info(f"Opening in {get_editor()}...")
                    config_content = _edit_config_in_editor(config_content)
                    console.print()
                    console.print("[dim]Edited config:[/dim]")
                    _preview_config(config_content)
                    console.print()

            # Write config
            _write_config(config_content, config_path)
            success(f"Configuration written to {config_path}")
            console.print()

    else:
        # Generic system - config is optional
        if not non_interactive:
            console.print(
                "[dim]On generic systems, a user.config is not required for basic "
                "Docker/Apptainer usage.[/dim]",
            )
            create_config = typer.confirm(
                "Would you like to create a user.config anyway?",
                default=False,
            )
            if create_config:
                info("Custom config creation not yet implemented for generic systems")
        console.print()

    # Validate config directory
    is_valid, message = _validate_config_dir(effective_config_dir)
    if not is_valid:
        error(f"Invalid config directory: {message}")
        raise typer.Exit(1)

    console.print(f"[green]Config directory:[/green] {effective_config_dir}")
    console.print()

    try:
        nvd_repo_raw = _find_nvd_repo()
        # Use stable path (latest symlink) for versioned installs
        nvd_repo = _get_stable_repo_path(nvd_repo_raw)
    except FileNotFoundError as e:
        error(str(e))
        raise typer.Exit(1) from e

    # Check if wrapper already exists
    wrapper_path = DEFAULT_WRAPPER_DIR / "nvd"
    if wrapper_path.exists() and not force:
        if non_interactive:
            warning(f"Wrapper script already exists: {wrapper_path}")
            warning("Use --force to overwrite")
        else:
            console.print(
                f"[yellow]Wrapper script already exists:[/yellow] {wrapper_path}",
            )
            overwrite = typer.confirm("Overwrite existing wrapper?", default=False)
            if not overwrite:
                info("Keeping existing wrapper script")
            else:
                _install_wrapper_script(nvd_repo, DEFAULT_WRAPPER_DIR)
                success(f"Wrapper script installed to {wrapper_path}")
    else:
        _install_wrapper_script(nvd_repo, DEFAULT_WRAPPER_DIR)
        success(f"Wrapper script installed to {wrapper_path}")

    # Determine default profile (CHTC uses chtc_htc profile from user.config)
    default_profile = "chtc_htc" if is_chtc else None
    preset_store = CHTC_DEFAULT_PRESET_STORE if is_chtc else None
    taxonomy_dir = CHTC_DEFAULT_TAXONOMY_DIR if is_chtc else None

    # Write setup.conf
    conf_path = _write_setup_conf(
        nvd_repo,
        effective_config_dir,
        default_profile,
        preset_store,
        taxonomy_dir,
    )
    success(f"Setup config written to {conf_path}")
    if default_profile:
        info(f"Default profile set to: {default_profile}")

    # Generate shell completions
    if detected_shell:
        completions_path = _generate_completions(detected_shell)
        success(f"Shell completions generated: {completions_path}")
    else:
        # Generate both if we can't detect
        for shell_type in ("bash", "zsh"):
            completions_path = _generate_completions(shell_type)
            info(f"Generated {shell_type} completions: {completions_path}")

    console.print()

    if not skip_shell_hook:
        if detected_shell is None:
            # Can't detect shell - print manual instructions
            warning("Could not detect shell")
            console.print()
            console.print("Add this line to your shell's RC file manually:")
            console.print(f'  [cyan]eval "$({SHELL_HOOK_MARKER})"[/cyan]')
            console.print()
        else:
            rc_file = _get_rc_file(detected_shell)

            if _is_hook_installed(rc_file):
                info(f"Shell hook already installed in {rc_file}")
            elif non_interactive:
                # Just install it
                if _install_shell_hook(rc_file):
                    success(f"Shell hook added to {rc_file}")
                else:
                    warning(f"Could not modify {rc_file} (permission denied)")
                    console.print()
                    console.print("Add this line manually:")
                    console.print(f'  [cyan]eval "$({SHELL_HOOK_MARKER})"[/cyan]')
            else:
                # Ask first
                console.print(f"Add shell hook to {rc_file}?")
                console.print(f'  [dim]eval "$({SHELL_HOOK_MARKER})"[/dim]')
                add_hook = typer.confirm("Proceed?", default=True)

                if add_hook:
                    if _install_shell_hook(rc_file):
                        success(f"Shell hook added to {rc_file}")
                    else:
                        warning(f"Could not modify {rc_file} (permission denied)")
                        console.print()
                        console.print("Add this line manually:")
                        console.print(f'  [cyan]eval "$({SHELL_HOOK_MARKER})"[/cyan]')
                else:
                    info("Skipping shell hook installation")
                    console.print()
                    console.print("To install later, add this to your RC file:")
                    console.print(f'  [cyan]eval "$({SHELL_HOOK_MARKER})"[/cyan]')

            console.print()
    else:
        info("Skipping shell hook installation (--skip-shell-hook)")
        console.print()

    if is_chtc and not skip_container:
        sif_path = _get_container_path()

        if sif_path.exists():
            info(f"Container image already exists: {sif_path}")
            if not non_interactive:
                repull = typer.confirm("Re-pull container image?", default=False)
                if repull:
                    console.print()
                    console.print(
                        "Pulling container image (~2GB)... [dim]This may take a few minutes.[/dim]",
                    )
                    pull_success, pull_message = _pull_apptainer_image()
                    if pull_success:
                        success(pull_message)
                    else:
                        warning(pull_message)
                        console.print()
                        console.print("You can download manually later with:")
                        console.print(
                            f"  [cyan]curl -fL -o {sif_path} {CONTAINER_IMAGE_URL}[/cyan]",
                        )
        elif non_interactive:
            # In non-interactive mode, skip container pull by default
            info("Skipping container pull in non-interactive mode")
            console.print()
            console.print("Download manually with:")
            console.print(
                f"  [cyan]curl -fL -o {sif_path} {CONTAINER_IMAGE_URL}[/cyan]",
            )
        else:
            console.print()
            console.print(
                "Would you like to pull the container image now? [dim](~2GB download)[/dim]",
            )
            pull_now = typer.confirm("Proceed?", default=True)

            if pull_now:
                console.print()
                console.print(
                    "Pulling container image... [dim]This may take a few minutes.[/dim]",
                )
                pull_success, pull_message = _pull_apptainer_image()
                if pull_success:
                    success(pull_message)
                else:
                    warning(pull_message)
                    console.print()
                    console.print("You can download manually later with:")
                    console.print(
                        f"  [cyan]curl -fL -o {sif_path} {CONTAINER_IMAGE_URL}[/cyan]",
                    )
            else:
                info("Skipping container pull")
                console.print()
                console.print("Download manually later with:")
                console.print(
                    f"  [cyan]curl -fL -o {sif_path} {CONTAINER_IMAGE_URL}[/cyan]",
                )

        console.print()

    elif is_chtc and skip_container:
        info("Skipping container pull (--skip-container)")
        console.print()
        console.print("Download manually later with:")
        sif_path = _get_container_path()
        console.print(f"  [cyan]curl -fL -o {sif_path} {CONTAINER_IMAGE_URL}[/cyan]")
        console.print()

    success("Setup complete!")
    console.print()
    if detected_shell:
        console.print(
            f"Run [cyan]source {_get_rc_file(detected_shell)}[/cyan] "
            "or start a new shell to activate.",
        )
    else:
        console.print("Start a new shell to activate.")
    console.print()


@setup_app.command("shell-hook")
def shell_hook(
    shell: str | None = typer.Option(
        None,
        "--shell",
        help="Shell type (bash, zsh). Auto-detected from $SHELL if not specified.",
    ),
) -> None:
    """
    Output shell integration code.

    This command outputs shell code that should be added to your RC file
    (~/.bashrc or ~/.zshrc). The code sets up:

    1. PATH to include the nvd wrapper
    2. NVD_CONFIG_DIR environment variable
    3. Shell completions for the nvd command

    Typically installed via 'nvd setup', but can be used manually:

        # Add to ~/.bashrc or ~/.zshrc:
        eval "$(nvd setup shell-hook)"

        # Or specify shell explicitly:
        eval "$(nvd setup shell-hook --shell zsh)"
    """
    # Detect shell (use provided or auto-detect)
    detected_shell = shell or _detect_shell()

    if detected_shell is None:
        # Can't detect shell - print generic message to stderr,
        # but still output something usable
        stderr_console.print(
            "[yellow]⚠[/yellow]  Could not detect shell. Assuming bash-compatible syntax.",
        )
        detected_shell = "bash"

    if detected_shell not in ("bash", "zsh"):
        error(f"Unsupported shell: {detected_shell}. Only bash and zsh are supported.")
        raise typer.Exit(1)

    # Read config_dir from setup.conf if it exists. The ~/.nvd fallback keeps
    # CHTC shell startup working before NVD_CONFIG_DIR has been exported.
    setup_conf_path = get_setup_conf_path()
    if not setup_conf_path.exists():
        setup_conf_path = INSTALL_HOME / "setup.conf"
    config_dir_value = str(get_config_dir())
    taxonomy_dir_value: str | None = None
    preset_store_value: str | None = None

    if setup_conf_path.exists():
        for line in setup_conf_path.read_text().splitlines():
            if line.startswith("NVD_CONFIG_DIR="):
                config_dir_value = line.split("=", 1)[1].strip()
            elif line.startswith("NVD_TAXONOMY_DB="):
                taxonomy_dir_value = line.split("=", 1)[1].strip()
            elif line.startswith("NVD_PRESET_STORE="):
                preset_store_value = line.split("=", 1)[1].strip()

    # Path to static completions file
    completions_file = Path(config_dir_value) / f"completions.{detected_shell}"
    preset_store_export = (
        f'\n# Shared preset store\nexport NVD_PRESET_STORE="{preset_store_value}"\n'
        if preset_store_value
        else ""
    )
    taxonomy_dir_export = (
        f'\n# Taxonomy cache visible to worker nodes\nexport NVD_TAXONOMY_DB="{taxonomy_dir_value}"\n'
        if taxonomy_dir_value
        else ""
    )

    # Output shell code to stdout (this is what gets eval'd)
    # Using print() directly to avoid Rich formatting
    shell_code = f"""\
# NVD shell integration
# Generated by nvd v{__version__}

# Wrapper script location
export PATH="$HOME/.local/bin:$PATH"

# NVD configuration directory
export NVD_CONFIG_DIR="{config_dir_value}"
{taxonomy_dir_export}
{preset_store_export}
# Shell completions ({detected_shell})
# Sourced from static file for fast shell startup
if [[ -f "{completions_file}" ]]; then
    source "{completions_file}"
fi
"""
    print(shell_code)  # noqa: T201 — intentional CLI output
