"""Tests for setup helpers after the v3 config-dir refactor."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING
from unittest.mock import patch

from py_nvd import __version__
from py_nvd.cli.commands.setup import (
    _detect_shell,
    _generate_setup_conf,
    _generate_wrapper_script,
    _is_oconnor_chtc,
    _validate_config_dir,
)

if TYPE_CHECKING:
    import pytest


def test_detect_shell_bash(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("SHELL", "/bin/bash")
    assert _detect_shell() == "bash"


def test_is_oconnor_chtc_true_on_matching_host() -> None:
    with (
        patch("socket.gethostname", return_value="oconnor-ap2001"),
        patch("socket.getfqdn", return_value="oconnor-ap2001.chtc.wisc.edu"),
    ):
        assert _is_oconnor_chtc()


def test_generate_setup_conf_writes_config_dir() -> None:
    conf = _generate_setup_conf(
        Path("/opt/nvd"),
        Path("/example/nvd-config"),
        default_profile="chtc_htc",
    )

    assert "NVD_REPO=/opt/nvd" in conf
    assert "NVD_CONFIG_DIR=/example/nvd-config" in conf
    assert "NVD_DEFAULT_PROFILE=chtc_htc" in conf
    assert "NVD_STATE_DIR" not in conf


def test_generate_wrapper_script_points_to_repo() -> None:
    script = _generate_wrapper_script(Path("/opt/nvd"))
    assert f"Generated by: nvd setup v{__version__}" in script
    assert 'NVD_REPO="/opt/nvd"' in script


def test_validate_config_dir_creates_missing_directory(tmp_path: Path) -> None:
    target = tmp_path / "nvd-config"
    valid, message = _validate_config_dir(target)
    assert valid, message
    assert target.is_dir()
