"""Tests for setup helpers after the v3 config-dir refactor."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING
from unittest.mock import patch

from typer.testing import CliRunner

from py_nvd import __version__
from py_nvd.cli.commands.setup import (
    CHTC_DEFAULT_CONFIG_DIR,
    CHTC_DEFAULT_PRESET_STORE,
    _detect_shell,
    _generate_setup_conf,
    _generate_wrapper_script,
    _guard_bash_completion_script,
    _is_oconnor_chtc,
    _validate_config_dir,
    setup_app,
)

if TYPE_CHECKING:
    import pytest


runner = CliRunner()


def test_detect_shell_bash(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("SHELL", "/bin/bash")
    assert _detect_shell() == "bash"


def test_is_oconnor_chtc_true_on_matching_host() -> None:
    with (
        patch("socket.gethostname", return_value="oconnor-ap2001"),
        patch("socket.getfqdn", return_value="oconnor-ap2001.chtc.wisc.edu"),
    ):
        assert _is_oconnor_chtc()


def test_generate_setup_conf_writes_config_dir() -> None:
    conf = _generate_setup_conf(
        Path("/opt/nvd"),
        Path("/example/nvd-config"),
        default_profile="chtc_htc",
    )

    assert "NVD_REPO=/opt/nvd" in conf
    assert "NVD_CONFIG_DIR=/example/nvd-config" in conf
    assert "NVD_DEFAULT_PROFILE=chtc_htc" in conf
    assert "NVD_STATE_DIR" not in conf


def test_generate_setup_conf_writes_chtc_preset_store() -> None:
    conf = _generate_setup_conf(
        Path.home() / ".nvd" / "latest",
        CHTC_DEFAULT_CONFIG_DIR,
        default_profile="chtc_htc",
        preset_store=CHTC_DEFAULT_PRESET_STORE,
    )

    assert f"NVD_CONFIG_DIR={Path.home() / '.nvd'}" in conf
    assert "NVD_PRESET_STORE=/staging/groups/oconnor_group/nvd/presets.sqlite" in conf
    assert "NVD_DEFAULT_PROFILE=chtc_htc" in conf
    assert "NVD_STATE_DIR" not in conf


def test_shell_hook_exports_preset_store_from_setup_conf(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    config_dir = tmp_path / "config"
    preset_store = tmp_path / "shared" / "presets.sqlite"
    config_dir.mkdir()
    (config_dir / "setup.conf").write_text(
        _generate_setup_conf(
            Path("/opt/nvd"),
            config_dir,
            default_profile="chtc_htc",
            preset_store=preset_store,
        ),
    )
    monkeypatch.setenv("NVD_CONFIG_DIR", str(config_dir))

    result = runner.invoke(setup_app, ["shell-hook", "--shell", "bash"])

    assert result.exit_code == 0, result.output
    assert f'export NVD_CONFIG_DIR="{config_dir}"' in result.output
    assert f'export NVD_PRESET_STORE="{preset_store}"' in result.output
    assert f"{config_dir / 'completions.bash'}" in result.output


def test_generate_wrapper_script_points_to_repo() -> None:
    script = _generate_wrapper_script(Path("/opt/nvd"))
    assert f"Generated by: nvd setup v{__version__}" in script
    assert 'NVD_REPO="/opt/nvd"' in script


def test_validate_config_dir_creates_missing_directory(tmp_path: Path) -> None:
    target = tmp_path / "nvd-config"
    valid, message = _validate_config_dir(target)
    assert valid, message
    assert target.is_dir()


def test_bash_completion_registration_is_guarded() -> None:
    script = """_nvd_completion() {
    return 0
}

complete -o default -F _nvd_completion nvd
"""

    guarded = _guard_bash_completion_script(script)

    assert "if type complete >/dev/null 2>&1; then" in guarded
    assert "    complete -o default -F _nvd_completion nvd" in guarded
    assert guarded.rstrip().endswith("fi")
